=== Advent51/ccc/doc/schema/com_2012.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:webdetails/com/2012" 
        xmlns:com="urn:webdetails/com/2012" 
        elementFormDefault="qualified">
    
    <!-- 
        List(number) 
        
        Union(string, number)
        
        Union(string, number, List(number))
        
        List(Union(string, number))
        
        Union(string, number, List(Union(string, number))
        
        Invalid combinations:
          X  List(List(.))
          X  List(Union(List(.), number))
        
        ......................................................
         
                /
          Value | * name  (Lists and Unions may be anonymous)
            ^   \
            |
            |              /
            |....... Union | * types -> Value (!cycle)
            |              \
            |
            |              /
            |....... List  | * elementType -> Item
            |              \
            |
            +....... Item
                       ^
                       |
                       |                     /
                       |.......... ItemUnion | * types -> Item
                       |                     \
                       |
                       |.......... Atom
                       |             ^
                       |             |
                       |             +...... Primitive
                       |
                       |                   /
                       +.......... Complex | * abstract
                                        |  | * baseType -> Complex 
                                        |  \
                                        |                     /
                                        |                     | * name
                                        +........ >> Property | * required
                                                              | * default
                                                              \ 
     -->
     
    <element name="model" type="com:ModelType">
        <key name="class_key">
            <selector xpath="complexType" />
            <field xpath="@name" />
        </key>
        <key name="atom_key">
            <selector xpath="atomType" />
            <field xpath="@name" />
        </key>
        
        <unique name="model_documentation_format__key">
           <selector xpath="." />
           <field xpath="documentation/@format" />
        </unique>
        <unique name="class_documentation_format__key">
           <selector xpath="complexType" />
           <field xpath="documentation/@format" />
        </unique>
        <unique name="property_documentation_format__key">
           <selector xpath="complexType/property" />
           <field xpath="documentation/@format" />
        </unique>
        
        <keyref name="class_keyref" refer="com:class_key">
            <selector xpath="complexType" />
            <field xpath="@base" />
        </keyref>
    </element>
    
    <!-- To be used within documentation elements -->
    <element name="link">
        <complexType>
            <attribute name="href" type="string" use="required" />
        </complexType>
    </element>
    
    <complexType name="ModelType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0" maxOccurs="unbounded">
	            <element name="complexType" type="com:ComplexTypeType" />
	            <element name="atomType" type="com:AtomTypeType" />
	       </choice>
       </sequence>
    </complexType>
    
    <complexType name="ComplexTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
        <attribute name="abstract" type="boolean" default="false" />
    </complexType>
    
    <complexType name="PropertyType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" default="string" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" />
        <attribute name="category" type="string" />
    </complexType>
    
    <complexType name="AtomTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="atom" type="com:AtomType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
    </complexType>
    
    <complexType name="AtomType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="value" type="anySimpleType" use="required" />
    </complexType>
    
    
    <complexType name="DocumentationType" mixed="true">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <any namespace="##any" processContents="lax" />
        </sequence>
        
        <attribute name="format" type="com:DocumentationFormatType" use="optional" />
    </complexType>
    
    <simpleType name="ValueTypeType">
        <union memberTypes="com:PrimitiveTypeType string" />
    </simpleType>
    
    <simpleType name="PrimitiveTypeType">
        <restriction base="string">
           <enumeration value="literal" />
           <enumeration value="string" />
           <enumeration value="number" />
           <enumeration value="boolean" />
           <enumeration value="object" />
           <enumeration value="function" />
           <enumeration value="date" />
           <enumeration value="percentage" />
        </restriction>
    </simpleType>
    
    <simpleType name="IdType">
        <restriction base="NMTOKEN" />
    </simpleType>
    
    <simpleType name="DocumentationFormatType">
        <restriction base="string">
           <enumeration value="markdown" />
           <enumeration value="jsdoc" />
           <enumeration value="com" />
        </restriction>
    </simpleType>
</schema>

=== Advent51/ccc/doc/model/marks/bar.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="BarExtensionPoint" space="pvc.options.marks" base="pvc.options.marks.MarkExtensionPoint">
         <c:documentation>
            The class of protovis Bar extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Bar.html" />.
        </c:documentation>
        
        <c:property name="fillStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The fill color of the bar.
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Bar.html#fillStyle" />.
            </c:documentation>
        </c:property>
        
        <c:property name="strokeStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The border stroke color of the bar. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Bar.html#strokeStyle" />.
            </c:documentation>
        </c:property>
        
        <c:property name="lineWidth" type="number">
            <c:documentation>
                The width of the border of the bar. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Bar.html#lineWidth" />.
            </c:documentation>
        </c:property>
        
        <c:property name="width" type="number">
            <c:documentation>
                The width of the bar. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Bar.html#width" />.
            </c:documentation>
        </c:property>
        
        <c:property name="height" type="number">
            <c:documentation>
                The height of the bar. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Bar.html#height" />.
            </c:documentation>
        </c:property>
    </c:complexType>
</c:model>

=== Advent51/ccc/doc/model/axes/axis-cartesian-discrete.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="DiscreteCartesianAxis"
                   space="pvc.options.axes"
                   base="pvc.options.axes.CartesianAxis"
                   abstract="true"
                   use="expanded"
                   facets="pvc.options.axes.DiscreteCartesianAxisFacet">
        <c:documentation>
            The options documentation class of the cartesian axis panel
            for discrete scale type.
            
            For additional information, please see <c:link to="pvc.options.axes.CartesianAxis" />.
        </c:documentation>
        
        <!-- HACK due to kettle cde job limitation -->
        <c:property name="" type="">
        </c:property>
    </c:complexType>
    
    <c:complexType name="FlattenedDiscreteCartesianAxis"
                   space="pvc.options.axes"
                   base="pvc.options.axes.DiscreteCartesianAxis"
                   use="expanded"
                   facets="pvc.options.axes.CartesianAxisTicksFacet">
        <c:documentation>
            The options documentation class of the cartesian axis panel
            for flattened and discrete scale type.
            
            For additional information, please see <c:link to="pvc.options.axes.CartesianAxis" />.
        </c:documentation>
        
        <!-- HACK due to kettle cde job limitation -->
        <c:property name="" type="">
        </c:property>
    </c:complexType>
    
    <c:complexType name="AnyDiscreteCartesianAxis"
                   space="pvc.options.axes"
                   base="pvc.options.axes.DiscreteCartesianAxis"
                   use="expanded"
                   facets="pvc.options.axes.CartesianAxisTicksFacet">
        <c:documentation>
            The options documentation class of the cartesian axis panel
            for discrete scale type.
            
            For additional information, please see <c:link to="pvc.options.axes.CartesianAxis" />.
        </c:documentation>
        
         <c:property name="composite" type="boolean" default="false" category="Discrete > General">
            <c:documentation>
                Indicates if the axis should show 
                discrete multi-dimensional data in 
                a hierarchical form, when <tt>true</tt>,
                or a flattened form, when <tt>false</tt>
                (applies to discrete axes).
                
                Flattened axes, present multi-dimensional roles
                by joining the multiple values with a separator character.
            </c:documentation>
        </c:property>
        
    </c:complexType>
    
    <c:facetType name="DiscreteCartesianAxisFacet" space="pvc.options.axes">
        <c:documentation>
            The options documentation class of the cartesian axis panel
            for discrete scale types.
        </c:documentation>
        
        <c:property name="clickAction" type="pvc.options.varia.StandardAction" category="Discrete > Actions">
            <c:documentation>
                A callback function that is called
                when the user clicks on a tick label
                (applies to discrete axes).
            </c:documentation>
        </c:property>
        
        <c:property name="doubleClickAction" type="pvc.options.varia.StandardAction" category="Discrete > Actions">
            <c:documentation>
                A callback function that is called
                when the user double-clicks on a tick label
                (applies to discrete axes).
            </c:documentation>
        </c:property>
    </c:facetType>
    
</c:model>

=== Advent51/ccc/doc/model/marks/rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="RuleExtensionPoint" space="pvc.options.marks" base="pvc.options.marks.MarkExtensionPoint">
         <c:documentation>
            The class of protovis Rule extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Rule.html" />.
        </c:documentation>
        
        <c:property name="width" type="number">
            <c:documentation>
                The width of the rule, when it is horizontal.
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Rule.html#width" />.
            </c:documentation>
        </c:property>
        
        <c:property name="height" type="number">
            <c:documentation>
                The height of the rule, when it is vertical. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Rule.html#height" />.
            </c:documentation>
        </c:property>
        
        <c:property name="strokeStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The stroke color of the rule. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Rule.html#strokeStyle" />.
            </c:documentation>
        </c:property>
        
        <c:property name="lineWidth" type="number">
            <c:documentation>
                The line width of the rule.
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Rule.html#lineWidth" />.
            </c:documentation>
        </c:property>
        
    </c:complexType>
    
</c:model>

=== Advent51/ccc/doc/model/panels/legend.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="LegendPanelOptions" 
                   space="pvc.options.panels" 
                   base="pvc.options.panels.CommonDockedPanelOptions">
        <c:documentation>
            The options documentation class of the CCC legend panel.
            
            The default 
            <c:link to="pvc.options.panels.CommonDockedPanelOptions#position" />
            is <tt>'bottom'</tt>.
            
            The default 
            <c:link to="pvc.options.panels.CommonDockedPanelOptions#font" />
            is <tt>'10px sans-serif'</tt>.
            
            The default
            <c:link to="pvc.options.panels.CommonDockedPanelOptions#paddings" />
            is <tt>5</tt> pixels.
        </c:documentation>
        
        <c:property name="textMargin" type="number" default="6" category="Layout">
            <c:documentation>
                The space between the marker and the associated label, in pixel units.
            </c:documentation>
        </c:property>
        
        <c:property name="itemPadding" type="number" default="2.5" category="Layout">
            <c:documentation>
                Half the space between legend items, in pixel units.
            </c:documentation>
        </c:property>
        
        <c:property name="markerSize" type="number" default="15" category="Layout">
            <c:documentation>
                The width and height of the marker panel.
                
                The marker itself will be slightly smaller.
            </c:documentation>
        </c:property>
        
        <c:property name="drawLine" type="boolean" category="Style">
            <c:documentation>
                Forces a rule to be shown or not in the marker zone.
                
                The default value depends on the chart type.
            </c:documentation>
        </c:property>
        
        <c:property name="drawMarker" type="boolean" category="Style">
            <c:documentation>
                Forces a shape to be shown or not in the marker zone.
                
                The default value depends on the chart type.
            </c:documentation>
        </c:property>

        <c:property name="shape" type="pvc.options.varia.ShapeType" category="Style">
            <c:documentation>
                Forces a given shape to be used in the marker zone.
                
                The default value depends on the chart type.
            </c:documentation>
        </c:property>
        
        <c:property name="clickMode" type="pvc.options.varia.LegendClickMode" default="'toggleVisible'" category="Style">
            <c:documentation>
                What happens when the user clicks a legend item. 
            </c:documentation>
        </c:property>
        
        <c:property name="extensionPoints" type="pvc.options.ext.LegendPanelExtensionPoints" category="Style">
            <c:documentation>
                The extension points provided by the legend panel.
            </c:documentation>
         </c:property>
    </c:complexType>
    
    <c:complexType name="LegendPanelExtensionPoints" space="pvc.options.ext">
        <c:documentation>
            The extension points of the legend panel.
            
            To use an extension point you must find its full name: 
            join the prefix property name, 
            like <c:link to="#legendArea" />,
            with one of the properties of the type of the extension point,
            like <c:link to="pvc.options.marks.BarExtensionPoint#strokeStyle" />,
            with an "_" character in between,
            and obtain the name <tt>legendArea_strokeStyle</tt>.
        </c:documentation>
        
        <c:property name="legendArea" type="pvc.options.marks.PanelExtensionPoint">
            <c:documentation>
                The extension point of the top panel of the legend panel.
            </c:documentation>
        </c:property>
        
        <c:property name="legendPanel" type="pvc.options.marks.PanelExtensionPoint">
            <c:documentation>
                The extension point of legend item panels.
            </c:documentation>
        </c:property>
                
        <c:property name="legendLabel" type="pvc.options.marks.LabelExtensionPoint">
            <c:documentation>
                The extension point of the label of a legend item.
            </c:documentation>
        </c:property>
        
        <c:property name="legendDot" type="pvc.options.marks.DotExtensionPoint">
            <c:documentation>
                The extension point of the dot (the marker's shape) of a legend item.
            </c:documentation>
        </c:property>
        
        <c:property name="legendRule" type="pvc.options.marks.RuleExtensionPoint">
            <c:documentation>
                The extension point of the rule (the marker's line) of a legend item.
            </c:documentation>
        </c:property>
        
        <!--  Shouldn't this apply to "label" and "panel" EPs as well??
        <c:property name="legend2Dot" type="pvc.options.marks.DotExtensionPoint">
            <c:documentation>
                The extension point of the dot (the marker's shape) of 
                a legend item of the second group.
            </c:documentation>
        </c:property>
        
        <c:property name="legend2Rule" type="pvc.options.marks.RuleExtensionPoint">
            <c:documentation>
                The extension point of the rule (the marker's line) of a legend item
                of the second group.
            </c:documentation>
        </c:property>
        -->
    </c:complexType>
    
</c:model>

=== Advent51/ccc/doc/model/plots/_plots.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:space name="pvc.options.plots">
        <c:documentation>
            The namespace of plot options classes. 
        </c:documentation>
    </c:space>
    
    <c:complexType name="PlotCommonOptions" space="pvc.options.plots" abstract="true">
        <c:documentation>
            The common options documentation class of all plots.
        </c:documentation>
        
        <c:property name="valuesVisible" default="false" type="boolean">
            <c:documentation>
                Indicates if value labels are shown next to the visual elements.
                
                Most charts have some form of showing labels
                with the <i>main</i> value next to the visual element.
                
                The default value really varies with the chart type,
                so be sure to confirm it in the most specific plot class.
            </c:documentation>
        </c:property>
        <c:property name="showValues" default="false" type="boolean">
            <c:documentation>
                <c:deprecated>Use <c:link to="#valuesVisible"/> instead.</c:deprecated>
                Indicates if value labels are shown next to the visual elements.
            </c:documentation>
        </c:property>
        <c:property name="valuesAnchor" default="" type="string">
            <c:documentation>
                The alignment of a value label 
                relative to its corresponding visual element position.
                
                The possible values depend on the chart type.
            </c:documentation>
        </c:property>
        
        <!-- 
        ValuesFont
        ValuesMask
        ColorAxis
         -->
    </c:complexType>
    
    <!-- 
    <c:include the="charts/common.xml" />
    
    <c:include the="charts/bullet.xml" />
    
	<c:include the="charts/cartesian-common.xml" />
	
	<c:include the="charts/categorical-common.xml" />
	-->
	<!-- CATEGORICAL
	<c:include the="charts/box.xml" />
	<c:include the="charts/heat-grid.xml" />
	 -->
	<!-- BAR
	<c:include the="charts/bar-common.xml" />
	<c:include the="charts/bar.xml" />
	<c:include the="charts/bar-normalized.xml" />
	<c:include the="charts/waterfall.xml" />
	 -->
	<!-- POINT
	<c:include the="charts/point-common.xml" />
    <c:include the="charts/line.xml" />
    <c:include the="charts/line-stacked.xml" />
    <c:include the="charts/dot.xml" />
    <c:include the="charts/dot-stacked.xml" />
    <c:include the="charts/area.xml" />
    <c:include the="charts/area-stacked.xml" />
    -->
	<!-- METRIC POINT
	<c:include the="charts/point-metric-common.xml" />
	<c:include the="charts/line-metric.xml" />
	<c:include the="charts/dot-metric.xml" />
	 -->
</c:model>

=== Advent51/ccc/doc/model/panels/axis-cartesian-discrete.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="DiscreteCartesianAxisOptions" 
                   space="pvc.options.panels" 
                   base="pvc.options.panels.CartesianAxisOptions">
        <c:documentation>
            The options documentation class of the cartesian axis panel
            for discrete scale types.
            
            For more information about cartesian axes 
            please see the comments in the base class
            <c:link to="pvc.options.panels.CartesianAxisOptions" />.
            
            For more information on a specific
            type of discrete axis,   
            please see:
            <c:link to="pvc.options.panels.FlattenedCartesianAxisOptions" />
            and
            <c:link to="pvc.options.panels.HierarchicalCartesianAxisOptions" />.
        </c:documentation>
        
        <c:property name="composite" type="boolean" default="false" category="General">
            <c:documentation>
                Indicates if the axis should show 
                discrete multi-dimensional data in 
                a hierarchical form, when <tt>true</tt>,
                or a flattened form, when <tt>false</tt>.
            </c:documentation>
        </c:property>
        
        <c:property name="clickAction" type="pvc.options.varia.StandardAction" category="Actions">
            <c:documentation>
                A callback function that is called
                when the user clicks on a tick label.
            </c:documentation>
        </c:property>
        
        <c:property name="doubleClickAction" type="pvc.options.varia.StandardAction" category="Actions">
            <c:documentation>
                A callback function that is called
                when the user double-clicks on a tick label.
            </c:documentation>
        </c:property>
    </c:complexType>
    
</c:model>
