=== Advent51/ccc/doc/schema/com_2012.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:webdetails/com/2012" 
        xmlns:com="urn:webdetails/com/2012" 
        elementFormDefault="qualified">
    
    <!-- 
        List(number) 
        
        Union(string, number)
        
        Union(string, number, List(number))
        
        List(Union(string, number))
        
        Union(string, number, List(Union(string, number))
        
        Invalid combinations:
          X  List(List(.))
          X  List(Union(List(.), number))
        
        ......................................................
         
                /
          Value | * name  (Lists and Unions may be anonymous)
            ^   \
            |
            |              /
            |....... Union | * types -> Value (!cycle)
            |              \
            |
            |              /
            |....... List  | * elementType -> Item
            |              \
            |
            +....... Item
                       ^
                       |
                       |                     /
                       |.......... ItemUnion | * types -> Item
                       |                     \
                       |
                       |.......... Atom
                       |             ^
                       |             |
                       |             +...... Primitive
                       |
                       |                   /
                       +.......... Complex | * abstract
                                        |  | * baseType -> Complex 
                                        |  \
                                        |                     /
                                        |                     | * name
                                        +........ >> Property | * required
                                                              | * default
                                                              \ 
     -->
     
    <element name="model" type="com:ModelType">
        <key name="class_key">
            <selector xpath="complexType" />
            <field xpath="@name" />
        </key>
        <key name="atom_key">
            <selector xpath="atomType" />
            <field xpath="@name" />
        </key>
        
        <unique name="model_documentation_format__key">
           <selector xpath="." />
           <field xpath="documentation/@format" />
        </unique>
        <unique name="class_documentation_format__key">
           <selector xpath="complexType" />
           <field xpath="documentation/@format" />
        </unique>
        <unique name="property_documentation_format__key">
           <selector xpath="complexType/property" />
           <field xpath="documentation/@format" />
        </unique>
        
        <keyref name="class_keyref" refer="com:class_key">
            <selector xpath="complexType" />
            <field xpath="@base" />
        </keyref>
    </element>
    
    <!-- To be used within documentation elements -->
    <element name="link">
        <complexType>
            <attribute name="href" type="string" use="required" />
        </complexType>
    </element>
    
    <complexType name="ModelType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0" maxOccurs="unbounded">
	            <element name="complexType" type="com:ComplexTypeType" />
	            <element name="atomType" type="com:AtomTypeType" />
	       </choice>
       </sequence>
    </complexType>
    
    <complexType name="ComplexTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
        <attribute name="abstract" type="boolean" default="false" />
    </complexType>
    
    <complexType name="PropertyType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" default="string" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" />
        <attribute name="category" type="string" />
    </complexType>
    
    <complexType name="AtomTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="atom" type="com:AtomType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
    </complexType>
    
    <complexType name="AtomType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="value" type="anySimpleType" use="required" />
    </complexType>
    
    
    <complexType name="DocumentationType" mixed="true">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <any namespace="##any" processContents="lax" />
        </sequence>
        
        <attribute name="format" type="com:DocumentationFormatType" use="optional" />
    </complexType>
    
    <simpleType name="ValueTypeType">
        <union memberTypes="com:PrimitiveTypeType string" />
    </simpleType>
    
    <simpleType name="PrimitiveTypeType">
        <restriction base="string">
           <enumeration value="literal" />
           <enumeration value="string" />
           <enumeration value="number" />
           <enumeration value="boolean" />
           <enumeration value="object" />
           <enumeration value="function" />
           <enumeration value="date" />
           <enumeration value="percentage" />
        </restriction>
    </simpleType>
    
    <simpleType name="IdType">
        <restriction base="NMTOKEN" />
    </simpleType>
    
    <simpleType name="DocumentationFormatType">
        <restriction base="string">
           <enumeration value="markdown" />
           <enumeration value="jsdoc" />
           <enumeration value="com" />
        </restriction>
    </simpleType>
</schema>

=== Advent51/ccc/doc/model/marks/area.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="AreaExtensionPoint" space="pvc.options.marks" base="pvc.options.marks.MarkExtensionPoint">
         <c:documentation>
            The class of protovis Area extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html" />.
        </c:documentation>
        
        <c:property name="fillStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The fill color of the area.
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#fillStyle" />.
            </c:documentation>
        </c:property>
        
        <c:property name="strokeStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The border stroke color of the area. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#strokeStyle" />.
            </c:documentation>
        </c:property>
        
        <c:property name="lineWidth" type="number">
            <c:documentation>
                The width of the border of the bar. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#lineWidth" />.
            </c:documentation>
        </c:property>
        
        <c:property name="width" type="number">
            <c:documentation>
                The width of the area (use for horizontal orientation).
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#width" />.
            </c:documentation>
        </c:property>
        
        <c:property name="height" type="number">
            <c:documentation>
                The height of the area (use for vertical orientation). 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#height" />.
            </c:documentation>
        </c:property>
        
        <c:property name="interpolate" type="pvc.options.varia.LineAreaInterpolation">
            <c:documentation>
                How to interpolate the area between values. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#interpolate" />.
            </c:documentation>
        </c:property>
        
        <c:property name="tension" type="number">
            <c:documentation>
                The tension of cardinal splines,
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#tension" />.
            </c:documentation>
        </c:property>
        
        <!-- TODO 
        lineJoin
        lineCap
        strokeDasharray
        strokeMiterLimit
         -->
    </c:complexType>
</c:model>

=== Advent51/ccc/doc/model/marks/line.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="LineExtensionPoint" space="pvc.options.marks" base="pvc.options.marks.MarkExtensionPoint">
         <c:documentation>
            The class of protovis Line extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Line.html" />.
        </c:documentation>
        
        <c:property name="fillStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The fill color of the line.
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Line.html#fillStyle" />.
            </c:documentation>
        </c:property>
        
        <c:property name="strokeStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The border stroke color of the line. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Line.html#strokeStyle" />.
            </c:documentation>
        </c:property>
        
        <c:property name="lineWidth" type="number">
            <c:documentation>
                The width of the line. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Line.html#lineWidth" />.
            </c:documentation>
        </c:property>
        
        <c:property name="interpolate" type="pvc.options.varia.LineAreaInterpolation">
            <c:documentation>
                How to interpolate the line between values. 
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Line.html#interpolate" />.
            </c:documentation>
        </c:property>
        
        <c:property name="tension" type="number">
            <c:documentation>
                The tension of cardinal splines,
                
                See the associated protovis documentation at
                <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Line.html#tension" />.
            </c:documentation>
        </c:property>
        <!-- TODO 
        lineJoin
        lineCap
        strokeDasharray
        strokeMiterLimit
         -->
    </c:complexType>
</c:model>

=== Advent51/ccc/doc/model/marks/label.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="LabelExtensionPoint" 
                   space="pvc.options.marks"
                   use="expanded" 
                   base="pvc.options.marks.MarkExtensionPoint">
         <c:documentation>
            The class of protovis Label extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Label.html" />.
        </c:documentation>
        
        <c:property name="font" type="string">
            <c:documentation>
                The font used by the label.
                
                See the supported font format in 
                <c:link to="http://www.w3.org/TR/CSS2/fonts.html#font-shorthand" />
            </c:documentation>
        </c:property>
        
        <c:property name="text" type="string">
            <c:documentation>
                The text to show in the label.
            </c:documentation>
        </c:property>
        
        <c:property name="textStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The text color.
            </c:documentation>
        </c:property>
        
        <c:property name="textAngle" type="number" default="0">
            <c:documentation>
                The angle of the text, in <i>radian</i> units.
                
                The text angle is 0 at horizontal direction 
                and grows clock-wise. 
            </c:documentation>
        </c:property>
        
        <c:property name="textAlign" type="pvc.options.varia.TextAlignment">
            <c:documentation>
                The horizontal text alignment.
            </c:documentation>
        </c:property>
        
        <c:property name="textBaseline" type="pvc.options.varia.TextBaseline">
            <c:documentation>
                The vertical text alignment.
            </c:documentation>
        </c:property>
        
        <c:property name="textDecoration" type="string">
            <c:documentation>
                A CSS3 text decoration.
                
                See the syntax of this string at:
                <c:link to="http://www.w3.org/TR/2012/WD-css-text-decor-3-20121113/#text-decoration" />.
            </c:documentation>
        </c:property>
        
        <c:property name="textShadow" type="string">
            <c:documentation>
                A CSS3 text shadow.
                
                See the syntax of this string at:
                <c:link to="http://www.w3.org/TR/2012/WD-css-text-decor-3-20121113/#text-shadow-property" />.
            </c:documentation>
        </c:property>
    </c:complexType>
</c:model>
